# The URL the site will be built for
base_url = "https://privatepayments.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Choose a theme
theme = "terminimal"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# One of: blue, green, orange, pink, red.
# Defaults to blue.
accent_color = "green"

# One of: blue, dark, green, orange, pink, red.
# Enabling dark background will also modify primary font color
# to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "green"

# The logo text - defaults to "Terminimal theme"
logo_text = "Private Payments"

# Author name: when specified, modifies the default
# copyright text.
author = "Private Payments"

# Alternate text instead of the theme attribution
# meta = "META (TODO)"

menu_items = [
    {name = "overview", url = "$BASE_URL"},
    {name = "use cases", url = "$BASE_URL/use-cases"},
    {name = "integration guide", url = "$BASE_URL/integration-guide"}
]
